from pathlib import Path

path = Path('core/src/main/java/com/nyerahworks/balancepoint/BalancePointGame.java')
text = path.read_text()

old_dash = '''        TextureAttribute dashTextureAttribute = TextureAttribute.createDiffuse(instrumentTexture);\n        // Framebuffer-style UV orientation is wrong for a bike-mounted plane unless V is flipped.\n        dashTextureAttribute.offsetV = 1f;\n        dashTextureAttribute.scaleV = -1f;\n        Material dashScreenMat = new Material(dashTextureAttribute,\n                ColorAttribute.createDiffuse(Color.WHITE));'''
new_dash = '''        TextureAttribute dashTextureAttribute = TextureAttribute.createDiffuse(instrumentTexture);\n        // The screen quad is already oriented correctly in world space. Keep the texture\n        // unflipped so the LCD reads upright from the rider/chase camera.\n        Material dashScreenMat = new Material(dashTextureAttribute,\n                ColorAttribute.createDiffuse(Color.WHITE));'''
if old_dash not in text:
    raise SystemExit('dash texture block not found')
text = text.replace(old_dash, new_dash, 1)

old_camera = '''        } else {\n            float orbitPitch = MathUtils.clamp(lookPitch, -25f * MathUtils.degreesToRadians,\n                    30f * MathUtils.degreesToRadians);\n            float horizontalDistance = 5.7f * MathUtils.cos(orbitPitch);\n            float desiredHeight = 2.65f + 5.7f * MathUtils.sin(orbitPitch);\n            tempA.set(bikeX - sinView * horizontalDistance,\n                    Math.max(0.9f, desiredHeight),\n                    bikeZ - cosView * horizontalDistance);\n            float response = 1f - (float) Math.exp(-3.8f * dt);\n            camera.position.lerp(tempA, response);\n            tempB.set(bikeX + MathUtils.sin(yaw) * 2.2f,\n                    0.92f + MathUtils.sin(pitch) * 0.52f,\n                    bikeZ + MathUtils.cos(yaw) * 2.2f);\n            camera.up.set(Vector3.Y);\n            camera.lookAt(tempB);\n            camera.fieldOfView = 67f;\n        }'''
new_camera = '''        } else {\n            // Compact chase camera: keep a fixed physical distance from the bike and use\n            // FOV, not camera pull-back, to communicate speed. The old slow lerp created\n            // a velocity-dependent trailing error that made the camera drift farther away\n            // the faster the bike travelled.\n            float orbitPitch = MathUtils.clamp(lookPitch, -22f * MathUtils.degreesToRadians,\n                    24f * MathUtils.degreesToRadians);\n            float chaseDistance = 3.90f;\n            float horizontalDistance = chaseDistance * MathUtils.cos(orbitPitch);\n            float desiredHeight = 1.88f + chaseDistance * MathUtils.sin(orbitPitch);\n            tempA.set(bikeX - sinView * horizontalDistance,\n                    Math.max(0.82f, desiredHeight),\n                    bikeZ - cosView * horizontalDistance);\n\n            // At speed the camera nearly locks to the desired rig position so relative\n            // distance stays constant. At low speed a little smoothing keeps U-turns and\n            // orbit input from looking robotic.\n            float followResponse = Math.min(1f, dt * (11.5f + speed * 1.35f));\n            camera.position.lerp(tempA, followResponse);\n\n            float targetLead = 1.15f;\n            tempB.set(bikeX + MathUtils.sin(yaw) * targetLead,\n                    0.88f + MathUtils.sin(pitch) * 0.42f,\n                    bikeZ + MathUtils.cos(yaw) * targetLead);\n            camera.up.set(Vector3.Y);\n            camera.lookAt(tempB);\n\n            float speedFov = MathUtils.clamp(speed / 38f, 0f, 1f);\n            camera.fieldOfView = MathUtils.lerp(68f, 76f, speedFov);\n        }'''
if old_camera not in text:
    raise SystemExit('external camera block not found')
text = text.replace(old_camera, new_camera, 1)

path.write_text(text)
