from pathlib import Path

p = Path('core/src/main/java/com/nyerahworks/balancepoint/BalancePointGame.java')
s = p.read_text()

def rep(old, new, name):
    global s
    if old not in s:
        raise SystemExit(f'missing patch target: {name}')
    s = s.replace(old, new, 1)

rep('''    private static final float CONTACT_STIFFNESS = 52_000f;\n    private static final float CONTACT_DAMPING = 4_500f;\n    private static final float CONTACT_BUMP_START = 0.050f;\n    private static final float CONTACT_BUMP_STIFFNESS = 180_000f;''', '''    // Off-road suspension tune: softer spring, light compression damping so square edges do\n    // not kick the chassis upward, and stronger rebound damping so stored spring energy is\n    // dissipated instead of producing repeated pogo oscillations.\n    private static final float CONTACT_STIFFNESS = 44_000f;\n    private static final float CONTACT_COMPRESSION_DAMPING = 3_300f;\n    private static final float CONTACT_REBOUND_DAMPING = 6_800f;\n    private static final float CONTACT_BUMP_START = 0.060f;\n    private static final float CONTACT_BUMP_STIFFNESS = 115_000f;''', 'suspension constants')

rep('''        boolean leftArrowTouch = false;\n        boolean rightArrowTouch = false;\n        boolean shiftDownTouch = false;\n        boolean shiftUpTouch = false;\n        boolean lookTouch = false;\n        float requestedThrottle = 0f;\n        float requestedBrake = 0f;''', '''        boolean controlBoxTouch = false;\n        boolean shiftDownTouch = false;\n        boolean shiftUpTouch = false;\n        boolean lookTouch = false;\n        float requestedThrottle = 0f;\n        float requestedBrake = 0f;\n        float requestedSteer = 0f;\n        float requestedLean = 0f;''', 'input locals')

rep('''            if (x >= 0.03f && x < 0.16f && y > 0.66f && y < 0.91f) {\n                leftArrowTouch = true;\n                continue;\n            }\n            if (x >= 0.17f && x < 0.30f && y > 0.66f && y < 0.91f) {\n                rightArrowTouch = true;\n                continue;\n            }''', '''            // Rectangular two-axis rider control. Axes are independent rather than radial, so\n            // full steering and full fore/aft body movement can be commanded simultaneously.\n            // Input Y is top-origin: touching above center therefore maps to positive (forward) lean.\n            if (x >= 0.035f && x <= 0.295f && y >= 0.64f && y <= 0.94f) {\n                controlBoxTouch = true;\n                requestedSteer = applyAxisDeadzone(MathUtils.clamp((x - 0.165f) / 0.130f, -1f, 1f), 0.055f);\n                requestedLean = applyAxisDeadzone(MathUtils.clamp((0.790f - y) / 0.150f, -1f, 1f), 0.055f);\n                continue;\n            }''', 'steering touch zones')

rep('''        if (crashed || leftArrowTouch == rightArrowTouch) {\n            steerTarget = 0f;\n        } else {\n            steerTarget = leftArrowTouch ? 1.0f : -1.0f;\n        }\n\n        riderLean = 0f;\n        riderLeanTarget = 0f;''', '''        steerTarget = crashed || !controlBoxTouch ? 0f : requestedSteer;\n        riderLeanTarget = crashed || !controlBoxTouch ? 0f : requestedLean;''', 'steer lean targets')

rep('''        float steerResponse = 1.65f + Math.min(speed * 0.018f, 0.55f);\n        steer += (steerTarget - steer) * Math.min(1f, dt * steerResponse);''', '''        float steerResponse = 2.8f + Math.min(Math.abs(speed) * 0.020f, 0.65f);\n        steer += (steerTarget - steer) * Math.min(1f, dt * steerResponse);\n        // Body movement is deliberately slower than handlebar input, but still responsive\n        // enough to preload the bike before a crest or move forward under acceleration.\n        riderLean += (riderLeanTarget - riderLean) * Math.min(1f, dt * 5.2f);''', 'control response')

rep('''    private static float approach(float value, float target, float amount) {\n        if (value < target) return Math.min(value + amount, target);\n        return Math.max(value - amount, target);\n    }''', '''    private static float approach(float value, float target, float amount) {\n        if (value < target) return Math.min(value + amount, target);\n        return Math.max(value - amount, target);\n    }\n\n    private static float applyAxisDeadzone(float value, float deadzone) {\n        float magnitude = Math.abs(value);\n        if (magnitude <= deadzone) return 0f;\n        float rescaled = (magnitude - deadzone) / (1f - deadzone);\n        return Math.signum(value) * MathUtils.clamp(rescaled, 0f, 1f);\n    }''', 'axis deadzone helper')

rep('''        float rearContactForwardArm = rearForward\n                - WHEEL_RADIUS * rearContactState.normalForward;\n        float rearContactVerticalArm = rearVertical\n                - WHEEL_RADIUS * rearContactState.normalUp;\n        float frontContactForwardArm = frontForward\n                - WHEEL_RADIUS * frontContactState.normalForward;\n        float frontContactVerticalArm = frontVertical\n                - WHEEL_RADIUS * frontContactState.normalUp;''', '''        // Rider fore/aft input shifts the combined COM relative to both tire patches. Positive\n        // lean moves the COM forward, loading the front; negative lean moves it rearward. This\n        // changes force moments continuously instead of applying a scripted wheelie torque.\n        float comShiftForward = riderLean * RIDER_SHIFT;\n        float rearContactForwardArm = rearForward - comShiftForward\n                - WHEEL_RADIUS * rearContactState.normalForward;\n        float rearContactVerticalArm = rearVertical\n                - WHEEL_RADIUS * rearContactState.normalUp;\n        float frontContactForwardArm = frontForward - comShiftForward\n                - WHEEL_RADIUS * frontContactState.normalForward;\n        float frontContactVerticalArm = frontVertical\n                - WHEEL_RADIUS * frontContactState.normalUp;''', 'rider COM torque arms')

rep('''        float force = CONTACT_STIFFNESS * virtualCompression\n                - CONTACT_DAMPING * normalVelocity;''', '''        float damping = normalVelocity < 0f\n                ? CONTACT_COMPRESSION_DAMPING : CONTACT_REBOUND_DAMPING;\n        float force = CONTACT_STIFFNESS * virtualCompression\n                - damping * normalVelocity;''', 'asymmetric suspension damping')

rep('''        float steerLeftX = w * 0.095f;\n        float steerRightX = w * 0.235f;\n        float steerY = h * 0.18f;\n        float steerR = min * 0.064f;''', '''        float controlLeft = w * 0.035f;\n        float controlBottom = h * 0.06f;\n        float controlWidth = w * 0.260f;\n        float controlHeight = h * 0.300f;\n        float controlCenterX = controlLeft + controlWidth * 0.5f;\n        float controlCenterY = controlBottom + controlHeight * 0.5f;''', 'draw control geometry')

start = s.index('        // Steering pads.')
end = s.index('        // Shift buttons.', start)
s = s[:start] + '''        // Independent rectangular steer/lean pad. Horizontal: left -1 / right +1.\n        // Vertical: backward -1 / forward +1. Unlike a circular stick, the corners permit\n        // simultaneous full steering and full body movement.\n        shapes.setColor(1f, 1f, 1f, 0.075f);\n        shapes.rect(controlLeft, controlBottom, controlWidth, controlHeight);\n        shapes.setColor(1f, 1f, 1f, 0.16f);\n        shapes.rect(controlCenterX - 1f, controlBottom, 2f, controlHeight);\n        shapes.rect(controlLeft, controlCenterY - 1f, controlWidth, 2f);\n\n        float controlKnobX = controlCenterX + steerTarget * controlWidth * 0.5f;\n        float controlKnobY = controlCenterY + riderLeanTarget * controlHeight * 0.5f;\n        float knobHalf = min * 0.018f;\n        shapes.setColor(1f, 1f, 1f, 0.34f);\n        shapes.rect(controlKnobX - knobHalf, controlKnobY - knobHalf,\n                knobHalf * 2f, knobHalf * 2f);\n\n''' + s[end:]

p.write_text(s)
