plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nyerahworks.balancepoint'
    compileSdk 35

    defaultConfig {
        applicationId 'com.nyerahworks.balancepoint'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '0.1.1'
    }

    signingConfigs {
        debug {
            storeFile rootProject.file('.github/balancepoint-debug.keystore')
            storePassword 'balancepoint'
            keyAlias 'balancepoint'
            keyPassword 'balancepoint'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
