plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nyerahworks.balancepoint'
    compileSdk 36

    defaultConfig {
        applicationId 'com.nyerahworks.balancepoint'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '0.2.0'
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/robovm/ios/robovm.xml', 'META-INF/DEPENDENCIES.txt', 'META-INF/DEPENDENCIES', 'META-INF/dependencies.txt', '**/*.gwt.xml']
            pickFirsts += ['META-INF/LICENSE.txt', 'META-INF/LICENSE', 'META-INF/license.txt', 'META-INF/LGPL2.1', 'META-INF/NOTICE.txt', 'META-INF/NOTICE', 'META-INF/notice.txt']
        }
    }

    signingConfigs {
        debug {
            storeFile rootProject.file('.github/balancepoint-debug.keystore')
            storePassword 'balancepoint'
            keyAlias 'balancepoint'
            keyPassword 'balancepoint'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

configurations { natives }

dependencies {
    implementation 'com.badlogicgames.gdx:gdx:1.14.2'
    implementation 'com.badlogicgames.gdx:gdx-backend-android:1.14.2'

    natives 'com.badlogicgames.gdx:gdx-platform:1.14.2:natives-arm64-v8a'
    natives 'com.badlogicgames.gdx:gdx-platform:1.14.2:natives-armeabi-v7a'
    natives 'com.badlogicgames.gdx:gdx-platform:1.14.2:natives-x86_64'
}

tasks.register('copyAndroidNatives') {
    doFirst {
        file('libs/armeabi-v7a').mkdirs()
        file('libs/arm64-v8a').mkdirs()
        file('libs/x86_64').mkdirs()

        configurations.natives.copy().files.each { jar ->
            def outputDir = null
            if (jar.name.endsWith('natives-armeabi-v7a.jar')) outputDir = file('libs/armeabi-v7a')
            if (jar.name.endsWith('natives-arm64-v8a.jar')) outputDir = file('libs/arm64-v8a')
            if (jar.name.endsWith('natives-x86_64.jar')) outputDir = file('libs/x86_64')
            if (outputDir != null) {
                copy {
                    from zipTree(jar)
                    into outputDir
                    include '*.so'
                }
            }
        }
    }
}

tasks.matching { it.name.contains('merge') && it.name.contains('JniLibFolders') }.configureEach {
    dependsOn 'copyAndroidNatives'
}
